spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
    username: postgres
    password: postgres
front:
  path: C:\Luds\luds-front\dist\luds-front

server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /app