spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ludspizzaria
    username: postgres
    password: postgres
front:
  path: C:\Luds\luds-front\dist\luds-front

server:
  port: 8081
  compression:
    enabled: true
  servlet:
    context-path: /app