spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
    username: mvxpywjltcakct
    password: a2de2f6d9fb9100fc4679887a6d07af974b3562ab2d3ddb4bd61c69f75085d3c
front:
  path: C:\Luds\luds-front\dist\luds-front

server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /app