spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    #url: jdbc:postgresql://localhost:5432/luds-pizzaria
    #username: postgres
    #password: postgres
front:
  path: C:\Luds\luds-front\dist\luds-front

server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /app
